# Generated by Django 5.2.1 on 2025-05-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.BooleanField()),
                ('categoria', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('destinatario', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('data_transacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
